# Generated by Django 5.1.4 on 2024-12-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', help_text='Nome da Empresa', max_length=100, verbose_name='nome')),
            ],
        ),
    ]
